#include "partition_blocked_gen_undef.h"
#pragma pop_macro ("PARTITION_BLOCKED_GEN_TYPE_1")
#pragma pop_macro ("PARTITION_BLOCKED_GEN_TYPE_2")
#pragma pop_macro ("PARTITION_BLOCKED_GEN_TYPE_3")
#pragma pop_macro ("PARTITION_BLOCKED_GEN_VECTOR_LEN")
#pragma pop_macro ("PARTITION_BLOCKED_GEN_SUFFIX")
#pragma pop_macro ("PARTITION_BLOCKED_GEN_EXPAND")
#pragma pop_macro ("_TYPE_V")
#pragma pop_macro ("_TYPE_I")
#pragma pop_macro ("_TYPE_AD")
#pragma pop_macro ("partition_blocked_serial")
#pragma pop_macro ("partition_blocked_auto_serial")
