#undef CSC_UTIL_GEN_TYPE_1
#undef CSC_UTIL_GEN_TYPE_2
#undef CSC_UTIL_GEN_SUFFIX
#undef CSC_UTIL_GEN_EXPAND
#undef _TYPE_V
#undef _TYPE_I
#undef csc_col_indices
#undef csc_degrees_bandwidths_scatters
#undef csc_groups_per_row
#undef csc_column_distances_and_groupping
#undef csc_row_neighbours
#undef csc_cross_row_similarity
#undef csc_cross_row_neighbours
#undef csc_value_features
#undef csc_matrix_features
#undef csc_matrix_features_validation
#undef csc_plot
