#undef SAMPLESORT_GEN_TYPE_1
#undef SAMPLESORT_GEN_TYPE_2
#undef SAMPLESORT_GEN_TYPE_3
#undef SAMPLESORT_GEN_TYPE_4
#undef SAMPLESORT_GEN_SUFFIX
#undef SAMPLESORT_GEN_EXPAND
#undef _TYPE_V
#undef _TYPE_I
#undef _TYPE_BUCKET_I
#undef _TYPE_AD
#undef samplesort_concurrent
#undef samplesort
