#undef BUCKETSORT_GEN_TYPE_1
#undef BUCKETSORT_GEN_TYPE_2
#undef BUCKETSORT_GEN_TYPE_3
#undef BUCKETSORT_GEN_TYPE_4
#undef BUCKETSORT_GEN_SUFFIX
#undef BUCKETSORT_GEN_EXPAND
#undef _TYPE_V
#undef _TYPE_I
#undef _TYPE_BUCKET_I
#undef _TYPE_AD
#undef bucketsort_stable_serial
#undef bucketsort
