
#undef              CSR_UTIL_GEN_TYPE_1
#undef              CSR_UTIL_GEN_TYPE_2
#undef              CSR_UTIL_GEN_SUFFIX
#undef              CSR_UTIL_GEN_FUNCTION_ATTRIBUTES
#undef              CSR_UTIL_GEN_EXPAND
#undef              CSR_UTIL_GEN_EXPAND_TYPE
#undef              _TYPE_V
#undef              _TYPE_I
#undef              csr_row_indices
#undef              csr_count_short_rows
#undef              csr_count_distant_nonzeros
#undef              csr_degrees_bandwidths_scatters
#undef              csr_column_distances_and_groupping
#undef              csr_row_neighbours
#undef              csr_cross_row_similarity
#undef              csr_cross_row_neighbours
#undef              csr_cross_row_x_access_similarity
#undef              csr_matrix_features
#undef              csr_matrix_features_validation
#undef              csr_value_features
#undef              csr_plot
#undef              csr_row_size_histogram_plot
#undef              csr_cross_row_similarity_histogram_plot
#undef              csr_num_neigh_histogram_plot
#undef              csr_bandwidth_histogram_plot
#undef              csr_bandwidth_batch_nnz_bar_plot
#undef              csr_quantize_columns
#undef              csr_reorder_rows
