#undef CSR_UTIL_GEN_TYPE_1
#undef CSR_UTIL_GEN_TYPE_2
#undef CSR_UTIL_GEN_SUFFIX
#undef CSR_UTIL_GEN_EXPAND
#undef CSR_UTIL_GEN_EXPAND_TYPE
#undef _TYPE_V
#undef _TYPE_I
#undef csr_row_indices
#undef csr_degrees_bandwidths_scatters
#undef csr_groups_per_row
#undef csr_column_distances_and_groupping
#undef csr_row_neighbours
#undef csr_cross_row_similarity
#undef csr_cross_row_neighbours
#undef csr_value_features
#undef csr_matrix_features
#undef csr_matrix_features_validation
#undef csr_plot
